package wasmcloud:p3-multi-comps-demo@0.1.0;

interface receiver {
    invoke: func() -> result<string, string>;
}

world component {
    import wasi:cli/types@0.3.0-rc-2026-03-15;
    import wasi:clocks/types@0.3.0-rc-2026-03-15;

    export receiver;
}
